# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-20 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangobin', '0006_auto_20190120_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='highlighted_code',
            field=models.TextField(blank=True, help_text='Read only field. Will code syntax-highlited version of the original code.'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='hits',
            field=models.IntegerField(default=0, help_text='Read only field.Will update the hits'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='slug',
            field=models.SlugField(help_text='Read only filed. Will be filled automatically'),
        ),
    ]
